// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4-3NAuw1S5H81ym73pFMsr_AVD1u7PY',
    appId: '1:36751265954:web:b65c0176bcf7a9b13407fb',
    messagingSenderId: '36751265954',
    projectId: 'apiowl-81bc5',
    authDomain: 'apiowl-81bc5.firebaseapp.com',
    storageBucket: 'apiowl-81bc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj3G8pTRuasV-BlL7FCHG_wPdpli2dFuY',
    appId: '1:36751265954:android:c5c0c31a20330e6f3407fb',
    messagingSenderId: '36751265954',
    projectId: 'apiowl-81bc5',
    storageBucket: 'apiowl-81bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIKo9da-b3rwPkY21wlWaoF7rijQrzhTQ',
    appId: '1:36751265954:ios:535dc65301cd54db3407fb',
    messagingSenderId: '36751265954',
    projectId: 'apiowl-81bc5',
    storageBucket: 'apiowl-81bc5.firebasestorage.app',
    androidClientId: '36751265954-r3hca8jpvgkim1h4tblhmbqhqm0tkpvc.apps.googleusercontent.com',
    iosClientId: '36751265954-kg5b5m31tojij408dfl8pnabm1655rd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiowl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIKo9da-b3rwPkY21wlWaoF7rijQrzhTQ',
    appId: '1:36751265954:ios:535dc65301cd54db3407fb',
    messagingSenderId: '36751265954',
    projectId: 'apiowl-81bc5',
    storageBucket: 'apiowl-81bc5.firebasestorage.app',
    androidClientId: '36751265954-r3hca8jpvgkim1h4tblhmbqhqm0tkpvc.apps.googleusercontent.com',
    iosClientId: '36751265954-kg5b5m31tojij408dfl8pnabm1655rd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiowl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC4-3NAuw1S5H81ym73pFMsr_AVD1u7PY',
    appId: '1:36751265954:web:2cc63a3c9bcabee83407fb',
    messagingSenderId: '36751265954',
    projectId: 'apiowl-81bc5',
    authDomain: 'apiowl-81bc5.firebaseapp.com',
    storageBucket: 'apiowl-81bc5.firebasestorage.app',
  );

}